front_upper_window:
  type: "SHF3L"
  camera_serial: "2-001a"

front_lower_window:
  type: "Gemini335L"
  usb_port: "gmsl2-0"

rear_upper_window:
  type: "SHF3L"
  camera_serial: "2-001b"

rear_lower_window:
  type: "Gemini335L"
  usb_port: "gmsl2-1"


front_right_corner:
  type: "rplidar"
  udp_ip: "192.168.1.11"
  
rear_left_corner:
  type: "rplidar"
  udp_ip: "192.168.1.12"


