front_upper_window:
  type: "Gemini335L" #'none', 'plain', 'Gemini335L', 'SHF3L'
  usb_port: 'gmsl2-0'

front_lower_window:
  type: "SHF3L"
  video_device: /dev/gmsl_cam0

rear_upper_window:
  type: "Gemini335L"
  usb_port: 'gmsl2-1'

rear_lower_window:
  type: "SHF3L"
  video_device: /dev/gmsl_cam1

right_upper_window:
  type: "Gemini335L"

right_lower_window:
  type: "SHF3L"

left_upper_window:
  type: "Gemini335L"

left_lower_window:
  type: "SHF3L"




front_right_corner:
  type: "rplidar" #'none', 'rplidar'
  udp_ip: "192.168.1.11"

front_left_corner:
  type: "rplidar"

rear_right_corner:
  type: "rplidar"

rear_left_corner:
  type: "rplidar"
  udp_ip: "192.168.1.12"


